image: docker:latest
services:
- docker:dind
stages:
- build
- test
- release
- deploy
variables:
  SERVER_TEST_IMAGE: thanhpcc/petfilm:$CI_BUILD_REF_NAME
  SERVER_RELEASE_IMAGE: thanhpcc/petfilm:latest
before_script:
  - docker login -u thanhpcc -p $CI_DOCKERHUB_PASSWORD
build-server:
  stage: build
  script:
  - docker build --pull -t $SERVER_TEST_IMAGE

test-server:
  stage: test
  script:
    - docker run -d --name expertsdb rethinkdb
    - docker pull $SERVER_TEST_IMAGE
    - docker run --link mongodb:mongodb -e MONGO_URI=mongodb $SERVER_TEST_IMAGE npm test

release-server:
  stage: release
  script:
    - docker pull $SERVER_TEST_IMAGE
    - docker tag $SERVER_TEST_IMAGE $SERVER_RELEASE_IMAGE
    - docker push $SERVER_RELEASE_IMAGE
  only:
    - master
deploy:
  stage: deploy
  only:
    - master
  when: manual
  before_script:
    # Install ssh-agent, ldap if not already installed
    - apk add --update openssh
    # Run ssh-agent (inside the build environment)
    - eval $(ssh-agent -s)
    # Add the SSH key stored in SSH_PRIVATE_KEY variable to the agent store
    - echo "$SSH_PRIVATE_KEY" > ~/id_rsa && chmod 600 ~/id_rsa && ssh-add ~/id_rsa
    # For Docker builds disable host key checking. Be aware that by adding that
    # you are suspectible to man-in-the-middle attacks.
    # WARNING: Use this only with the Docker executor, if you use it with shell
    # you will overwrite your user's SSH config.
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  script:
    - ssh root@codezen.net "cd /root/bpwjs.deploy; make deploy"